apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: azure-agent
  name: azure-agent
spec:
  replicas: 1
  selector:
    app: azure-agent
    deploymentconfig: azure-agent
  strategy:
    resources:
      limits:
        cpu:     500m
        memory:  512Mi
      requests:
        cpu:     100m
        memory:  128Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: azure-agent
        deploymentconfig: azure-agent
    spec:
      containers:
      - env:
        - name: VSTS_AGENT
          value: Dev.Container
        - name: VSTS_ACCOUNT
          valueFrom:
            configMapKeyRef:
              key: VSTS_ACCOUNT
              name: azure-agent
        - name: VSTS_POOL
          valueFrom:
            configMapKeyRef:
              key: VSTS_POOL
              name: azure-agent
        - name: VSTS_TOKEN
          valueFrom:
            secretKeyRef:
              key: VSTS_TOKEN
              name: azure-agent-token
        image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard
        imagePullPolicy: Always
        name: azure-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-auth
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange