apiVersion: v1
kind: Template
metadata:
  name: azure-agent-secret-template
  annotations:
    description: "azure-agent secret template"
    tags: "azure-agent"
parameters:
- description: Azure DevOps Agent PAT
  name: AZP_TOKEN
  required: true
- description: PROXY Password
  name: PROXY_PASSWORD
  value: ""
objects:  
- apiVersion: v1
  stringData:
    AZP_TOKEN: ${AZP_TOKEN}
    PROXY_PASSWORD: ${PROXY_PASSWORD}
  kind: Secret
  metadata:
    name: azure-agent
  type: Opaque