apiVersion: v1
kind: Template
metadata:
  name: azure-agent-configmap-template
  annotations:
    description: "azure-agent configmap template"
    tags: "azure-agent"
parameters:
- description: Azure DevOps instance
  name: AZP_URL
  required: true  
- description: Azure DevOps Pool name
  name: AZP_POOL
  required: true
  value: ""
objects:
- apiVersion: v1
  data:
    AZP_URL: ${AZP_URL}
    AZP_POOL: ${AZP_POOL}
  kind: ConfigMap
  metadata:
    name: azure-agent