apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: azure-agent-deployment-template
  annotations:
    description: "azure-agent deployment template"
    tags: "azure-agent"
parameters:
- description: Image to use
  name: IMAGE
  required: false
  value: "azure-devops-agent:latest"
- description: CPU Limit
  name: CPU_LIMIT
  required: false
  value: "200m"
- description: Memory limit
  name: MEMORY_LIMIT
  required: false
  value: "300Mi"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: azure-devops-agent
    name: azure-devops-agent
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: azure-devops-agent
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: RollingUpdate  
    template:
      metadata:
        labels:
          app: azure-devops-agent
      spec:
        containers:
        - env:
          - name: AZP_URL
            valueFrom:
              configMapKeyRef:
                key: AZP_URL
                name: azure-agent
          - name: AZP_POOL
            valueFrom:
              configMapKeyRef:
                key: AZP_POOL
                name: azure-agent
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                key: AZP_TOKEN
                name: azure-agent
          - name: PROXY_URL
            valueFrom:
              configMapKeyRef:
                key: PROXY_URL
                name: azure-agent
          - name: PROXY_USERNAME
            valueFrom:
              configMapKeyRef:
                key: PROXY_USERNAME
                name: azure-agent
          - name: PROXY_PASSWORD
            valueFrom:
              secretKeyRef:
                key: PROXY_PASSWORD
                name: azure-agent
          image: ${IMAGE}
          imagePullPolicy: Always
          name: azure-devops-agent
          resources:
            limits: 
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          livenessProbe:
            exec:
              command:
              - /azp/health.sh
            initialDelaySeconds: 30
            periodSeconds: 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
